Updated for stability
x89/Shreddit pull request #180
Opened 2023-06-20 18:09 UTC by kayla-tokash

Before: it would stop after a few hundred actions because API limits
Now: it will continue to run after an API limit exception, but wait 10 seconds before continuing.

I also updated the "requirements.txt" to work for my system (I'm using OSX, but it should run on linux distributions and WSL)

2023-10-31 07:43 UTC, ilystsov requested changes
1. 134-136, 160-162:  Avoid looping eternally by setting maximum retries number
2. 144: Use f-strings instead of .format for consistency
3. 152: Catch more specific errors 
4. 153-156: Split the long string into multiple lines

2023-10-31 07:43 UTC, ilystsov commented on shreddit/shredder.py
> +                time.sleep(self._batch_cooldown)
```suggestion

        retries_count = 0 
        max_retries_count = 5
        while retries_count < max_retries_count:
            try:
                if self._keep_a_copy and self._save_directory:
                    self._save_item(item)
                if not self._trial_run and self._clear_vote:
                    try:
                        item.clear_vote()
                    except BadRequest as e:
                        self._logger.debug(f"Couldn't clear vote on {item}: {e}")
                if isinstance(item, Submission):
                    self._remove_submission(item)
                elif isinstance(item, Comment):
                    self._remove_comment(item)
                if not self._trial_run:
                    item.delete()
                break
            except BadRequest as e:
                self._logger.debug(
                    '''Encountered a problem with the API, 
                    probably ratelimiting thanks to bad admins'''
                )
                self._logger.error(f"Exception: {e}")
                self._logger.info(f"Waiting {self._batch_cooldown} seconds")
                time.sleep(self._batch_cooldown)
            retries_count += 1
        if retries_count == max_retries_count:
            self._logger.error("Max retry attempts reached. Unable to complete the operation.")
```
```

2023-10-31 17:08 UTC, ilystsov requested changes
Avoid looping eternally by setting maximum retries number

2023-10-31 17:08 UTC, ilystsov commented on shreddit/shredder.py
> +        while 1:
```suggestion
        MAX_RETRIES_COUNT = 5
        for retries_count in range(MAX_RETRIES_COUNT):
```

2023-10-31 17:08 UTC, ilystsov commented on shreddit/shredder.py
> +                time.sleep(self._batch_cooldown)
```suggestion
                time.sleep(self._batch_cooldown)
        else:
            self.__logger.error(
                "Max retry attempts reached. Unable to complete the operation"
            )
```

2023-10-31 17:11 UTC, ilystsov requested changes
Use f-strings instead of `.format` for consistency

2023-10-31 17:11 UTC, ilystsov commented on shreddit/shredder.py
> +                            self._logger.debug("Couldn't clear vote on {item}".format(item=item))
```suggestion
                            self._logger.debug(f"Couldn't clear vote on {item}")
```

2023-10-31 17:14 UTC, ilystsov requested changes
Split the long string into multiple lines

2023-10-31 17:14 UTC, ilystsov commented on shreddit/shredder.py
> +                self._logger.debug("Encountered a problem with the API, probably ratelimiting thanks to bad admins")
```suggestion
                self._logger.debug(
                    '''Encountered a problem with the API,
                    probably ratelimiting thanks to bad admins'''
                )
```

2023-10-31 17:16 UTC, ilystsov requested changes
Catch more specific errors

2023-10-31 17:16 UTC, ilystsov commented on shreddit/shredder.py
> +            except Exception as e:
```suggestion
            except BadRequest as e:
```

2023-11-28 23:41 UTC, kayla-tokash commented on shreddit/shredder.py
> +        while 1:
Considering how long the script takes to run, limiting max retries is not ideal. Add an option to run indefinitely if you're really trying to change it. I understand the distaste for `while 1` but the real experience is that it will not run to completion if you have a lot of posts because of the rate limiting.

2025-07-21 22:06 UTC, merged